=== balazsdukai/ogc-feat-geo-json/core/schemas/featurecollection.json
{
  "$schema": "https://json-schema.org/draft/2019-09/schema",
  "$id": "https://beta.schemas.opengis.net/json-fg/featurecollection.json",
  "title": "a JSON-FG Feature Collection",
  "description": "This JSON Schema is part of JSON-FG version 0.2.0-SNAPSHOT",
  "type": "object",
  "required": ["type", "features"],
  "properties": {
    "conformsTo": {
      "$ref": "conformsto.json"
    },
    "type": {
      "type": "string",
      "enum": ["FeatureCollection"]
    },
    "featureType": {
      "$ref": "featuretype.json"
    },
    "geometryDimension": {
      "type": "integer",
      "minimum": 0,
      "maximum": 3
    },
    "coordRefSys": {
      "$ref": "coordrefsys.json"
    },
    "links": {
      "type": "array",
      "items": {
        "$ref": "link.json"
      }
    },
    "features": {
      "type": "array",
      "items": {
        "$ref": "feature.json"
      }
    }
  }
}

=== balazsdukai/ogc-feat-geo-json/core/examples/airports.json
{
  "type": "FeatureCollection",
  "coordRefSys": "http://www.opengis.net/def/crs/EPSG/0/27700",
  "featureType": "Airport",
  "geometryDimension": 0,
  "features": [
    {
      "type": "Feature",
      "id": 1,
      "geometry": { "type": "Point", "coordinates": [-1.6930015, 60.3216821] },
      "properties": {"name": "Papa Stour Airstrip"},
      "place": { "type": "Point", "coordinates": [417057.93, 1159772.2] },
      "time": null
    },
    {
      "type": "Feature",
      "id": 2,
      "geometry": { "type": "Point", "coordinates": [-1.2922268, 59.8782666] },
      "properties": {"name": "Sumburgh Airport"},
      "place": { "type": "Point", "coordinates": [439723.69, 1110559.95] },
      "time": null
    },
    {
      "type": "Feature",
      "id": 46,
      "geometry": { "type": "Point", "coordinates": [0.9384272, 50.9556174] },
      "properties": {"name": "Lydd Airport"},
      "place": { "type": "Point", "coordinates": [606468.75, 121465.11] },
      "time": null
    }
  ],
  "links": [
    {
      "href": "https://demo.ldproxy.net/zoomstack/collections/airports/items?crs=http%3A%2F%2Fwww.opengis.net%2Fdef%2Fcrs%2FEPSG%2F0%2F27700&limit=50&f=jsonfg",
      "rel": "self",
      "type": "application/vnd.ogc.fg+json",
      "title": "Dieses Dokument"
    },
    {
      "href": "https://demo.ldproxy.net/zoomstack/collections/airports/items?crs=http%3A%2F%2Fwww.opengis.net%2Fdef%2Fcrs%2FEPSG%2F0%2F27700&limit=50&f=json",
      "rel": "alternate",
      "type": "application/geo+json",
      "title": "Dieses Dokument als GeoJSON"
    },
    {
      "href": "https://demo.ldproxy.net/zoomstack/collections/airports/items?crs=http%3A%2F%2Fwww.opengis.net%2Fdef%2Fcrs%2FEPSG%2F0%2F27700&limit=50&f=html",
      "rel": "alternate",
      "type": "text/html",
      "title": "Dieses Dokument als HTML"
    },
    {
      "href": "https://demo.ldproxy.net/zoomstack/collections/airports/schemas/collection",
      "rel": "describedby",
      "type": "application/schema+json",
      "title": "Schema of feature collections in 'Airports'"
    },
    {
      "href": "https://geojson.org/schema/FeatureCollection.json",
      "rel": "describedby",
      "type": "application/schema+json",
      "title": "This document is a GeoJSON FeatureCollection"
    }
  ]
}
